### ISSUE TITLE
Support for Digilent HS2

### ISSUE THREAD

**Issue by OliverSchwartz1** [jiegec/jtag-remote-server#2]
Hi,

I have some patches ready to add support for a Digilent HS2 adapter and buffering of MPSSE data. I can submit them if you're interested. I also have a HS3 adapter available which could be added as well.

**Comment by jiegec** [comment]
> Hi,
> 
> I have some patches ready to add support for a Digilent HS2 adapter and buffering of MPSSE data. I can submit them if you're interested. I also have a HS3 adapter available which could be added as well.

Sure, pull requests are welcome.
