### ISSUE TITLE
use case of  usb blaster

### ISSUE THREAD

**Issue by Juyash** [jiegec/jtag-remote-server#5]
I have successfully started the jtag server on 1309 using this code on HOST 1.

I would like to connect the server from altera programmer on HOST2, which require HOST1 IP(known) and password , which is unknown .

Could you please guide, how to proceed, also any other alternative to to connect to sever from HOST2 without password.

Kind regards
juy

**Comment by jiegec** [comment]
Currently quartus support is quite limited: the protocol is undocumented, and the current code does not implement enough of that for quartus to work. So you can only use this server to use usb blaster remotely via openocd, but not quartus.

**Comment by jiegec** [comment]
If you are interested in completing quartus jtag server support, pull requests are welcome. However, it is quite hard: although a open source version exists, but it is incomplete and hard to understand and port.

**Comment by Juyash** [comment]
Thank you for the clarification. Could you please share the open source version available.

**Comment by jiegec** [comment]
> Thank you for the clarification. Could you please share the open source version available.

https://github.com/intel/libaji_client https://github.com/intel/aji_openocd

**Comment by Juyash** [comment]
Hi ,  JTAGD server protocol; As I can see you are using some JTAG commands .

which client can connect to this JTAGD server and how ?

**Comment by jiegec** [comment]
> Hi , JTAGD server protocol; As I can see you are using some JTAG commands .
> 
> which client can connect to this JTAGD server and how ?

Quartus programmer is the client.

**Comment by Juyash** [comment]
so the Quartus programmer can connect to this server ? 
you already mentioned , "**the current code does not implement enough of that for quartus to work**"
So what I understood is that , it has JTAG commands which could be transmitted form the Quartus client, but the connection between the Quartus Client and this server is not implemented? please clarify.

**Comment by jiegec** [comment]
> so the Quartus programmer can connect to this server ? you already mentioned , "**the current code does not implement enough of that for quartus to work**" So what I understood is that , it has JTAG commands which could be transmitted form the Quartus client, but the connection between the Quartus Client and this server is not implemented? please clarify.

Quartus can connect to this server, but then immediately errored out due to unknown reasons. If we can reverse engineer the protocol, it is possible to let quartus speak to jtag-remote-server and program FPGA over network.

**Comment by Juyash** [comment]
ok. Thank you for the suggestion.
Could you please elaborate, how Quartus can connect, I want to try and see the error.

**Comment by jiegec** [comment]
See https://www.doulos.com/knowhow/fpga/remote-programming-of-fpgas/
